export default [
  {
    id: 0,
    logo: 'ЛоготипЛидер.jpg',
    photo1: 'photo/ok1.jpg',
    photo2: 'photo/noPhoto.jpg',
    text: 'Спортивный клуб «Лидер»',
    address1:'Москва, ул. Плещеева 3',
    address2:'г. Химки, ул. Лавочкина 13к5',
    address3:'',
    contacts: 'Контакты: т. 89259163736',
    link: 'https://vk.com/sportclub_leader',
    trener1: 'Михайлов Антон Александрович, кандидат в мастера спорта черный пояс IV дан',
    trener2: 'Гринева Дарья Андреевна, черный пояс I дан',
  },
  {
    id: 1,
    logo: 'IMG-20210722-WA0026.jpg',
    photo1: '20211212_165205.jpg',
    photo2: 'photo/spirin.jpg',
    text: 'Детско-юношеский спортивный клуб «Воин»',
    address1:'г.о. Лосино-Петровский, пос Свердловский, ул. Заречная 10',
    address2:'г. Щелково, мкр. Потаповский, д. 1 стр 1',
    address3:'',
    contacts: 'Контакты: т. 89267367425',
    link: 'https://vk.com/dusk_voin',
    trener1: 'Компаницкий Илья Сергеевич, мастер спорта черный пояс IV дан',
    trener2: 'Спирин Юрий Александрович, мастер спорта черный пояс I дан',
  },
  {
    id: 2,
    logo: 'ЛоготипRyzhovateam.jpeg',
    photo1: 'photo/Рыжова.jpeg',
    photo2: 'photo/noPhoto.jpg',
    text: 'Клуб - Ryzhova team',
    address1:'г. Видное, ул. Сухановская 1 стр.1, ТЦ «Аструм»',
    address2:'',
    address3:'',
    contacts: 'Контакты: т. 89859512518',
    link: '',
    trener1: 'Рыжова Надежда Андреевна, черный пояс II дан',
    trener2: 'Шатова Элина Олеговна, черный пояс I дан',
  },
  {
    id: 3,
    logo: 'ЛоготипKWON.jpg',
    photo1: 'photo/ratnix.jpeg',
    photo2: 'photo/Утенкова.jpeg',
    text: 'Спортивный клуб «КВОН»',
    address1:'Бирюлево-Западное Харьковский проезд 5 «А»',
    address2:'Чертаново-Южное ул. Газопровод 3 «А»',
    address3:'поселок Дубровский ул. Турова 6 «А»',
    contacts: 'Контакты: т. 89267238504',
    link: '',
    trener1: 'Ратных Иван Александрович, черный пояс IV дан',
    trener2: 'Утенкова Ольга Андреевна,Мастер спорта России международного класса черный пояс I дан',
  },
  {
    id: 4,
    logo: 'photo/noPhoto.jpg',
    photo1: 'photo/noPhoto.jpg',
    photo2: 'photo/noPhoto.jpg',
    text: 'Спортивный клуб «Атлант»',
    address1:'г. Талдом, ул. З. Голицыной, 24',
    address2:'',
    address3:'',
    contacts: 'Контакты: т. 89858577346',
    link: '',
    trener1: 'Латыпов Герман Робертович',
    trener2: '',
  },
]
